package com.fazada.model;
// Generated Dec 6, 2016 10:51:08 AM by Hibernate Tools 5.2.0.Beta1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Brand generated by hbm2java
 */
@Entity
@Table(name = "brand", catalog = "fazada")
public class Brand implements java.io.Serializable {

	private Integer brandId;
	private String brandName;

	public Brand() {
	}

	public Brand(String brandName) {
		this.brandName = brandName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "brand_id", unique = true, nullable = false)
	public Integer getBrandId() {
		return this.brandId;
	}

	public void setBrandId(Integer brandId) {
		this.brandId = brandId;
	}

	@Column(name = "brand_name", nullable = false, length = 45)
	public String getBrandName() {
		return this.brandName;
	}

	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}
}
