package com.fazada.model;
// Generated Dec 19, 2016 4:32:36 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;

/**
 * Cartdetail generated by hbm2java
 */
@Entity
@Table(name = "cartdetail", catalog = "fazada")
public class Cartdetail implements java.io.Serializable {

	private CartdetailId id;
	private Cart cart;
	private int quantity;

	public Cartdetail() {
	}

	public Cartdetail(CartdetailId id, Cart cart, int quantity) {
		this.id = id;
		this.cart = cart;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "cartId", column = @Column(name = "cartID", nullable = false)),
			@AttributeOverride(name = "productId", column = @Column(name = "productID", nullable = false)) })
	public CartdetailId getId() {
		return this.id;
	}

	public void setId(CartdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cartID", nullable = false, insertable = false, updatable = false)
	@JsonBackReference(value = "cart-cartdetail")
	public Cart getCart() {
		return this.cart;
	}

	public void setCart(Cart cart) {
		this.cart = cart;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
