package com.fazada.model;
// Generated Dec 19, 2016 4:32:36 PM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CartdetailId generated by hbm2java
 */
@Embeddable
public class CartdetailId implements java.io.Serializable {

	private int cartId;
	private int productId;

	public CartdetailId() {
	}

	public CartdetailId(int cartId, int productId) {
		this.cartId = cartId;
		this.productId = productId;
	}

	@Column(name = "cartID", nullable = false)
	public int getCartId() {
		return this.cartId;
	}

	public void setCartId(int cartId) {
		this.cartId = cartId;
	}

	@Column(name = "productID", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CartdetailId))
			return false;
		CartdetailId castOther = (CartdetailId) other;

		return (this.getCartId() == castOther.getCartId()) && (this.getProductId() == castOther.getProductId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCartId();
		result = 37 * result + this.getProductId();
		return result;
	}

}
