package com.fazada.model;
// Generated Dec 19, 2016 4:32:36 PM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Cart generated by hbm2java
 */
@Entity
@Table(name = "cart", catalog = "fazada")
public class Cart implements java.io.Serializable {

	private Integer cartId;
	private int userId;
	private Date updateDate;
	private Set<Cartdetail> cartdetails = new HashSet<Cartdetail>(0);

	public Cart() {
	}

	public Cart(int userId, Date updateDate) {
		this.userId = userId;
		this.updateDate = updateDate;
	}

	public Cart(int userId, Date updateDate, Set<Cartdetail> cartdetails) {
		this.userId = userId;
		this.updateDate = updateDate;
		this.cartdetails = cartdetails;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "cartID", unique = true, nullable = false)
	public Integer getCartId() {
		return this.cartId;
	}

	public void setCartId(Integer cartId) {
		this.cartId = cartId;
	}

	@Column(name = "userID", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updateDate", nullable = false, length = 10)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "cart", cascade = CascadeType.REMOVE)
	@JsonManagedReference(value = "cart-cartdetail")
	public Set<Cartdetail> getCartdetails() {
		return this.cartdetails;
	}

	public void setCartdetails(Set<Cartdetail> cartdetails) {
		this.cartdetails = cartdetails;
	}

}
