package com.fazada.model;
// Generated Dec 6, 2016 10:51:08 AM by Hibernate Tools 5.2.0.Beta1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Product generated by hbm2java
 */
@Entity
@Table(name = "product", catalog = "fazada")
public class Product implements java.io.Serializable {

	private int productId;
	private Brand brand;
	private String productName;
	private int price;
	private boolean status;
	private String img;
	private Set<Orderdetail> orderdetails = new HashSet<Orderdetail>(0);

	public Product() {
	}

	public Product(int productId, Brand brand, String productName, int price, boolean status, String img) {
		this.productId = productId;
		this.brand = brand;
		this.productName = productName;
		this.price = price;
		this.status = status;
		this.img = img;
	}

	public Product(int productId, Brand brand, String productName, int price, boolean status, String img,
			Set<Orderdetail> orderdetails) {
		this.productId = productId;
		this.brand = brand;
		this.productName = productName;
		this.price = price;
		this.status = status;
		this.img = img;
		this.orderdetails = orderdetails;
	}

	@Id

	@Column(name = "productID", unique = true, nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "brand_id", nullable = false)
	public Brand getBrand() {
		return this.brand;
	}

	public void setBrand(Brand brand) {
		this.brand = brand;
	}

	@Column(name = "productName", nullable = false, length = 45)
	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	@Column(name = "price", nullable = false)
	public int getPrice() {
		return this.price;
	}

	public void setPrice(int price) {
		this.price = price;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@Column(name = "img", nullable = false)
	public String getImg() {
		return img;
	}

	public void setImg(String img) {
		this.img = img;
	}
}
